spring:
  profiles:
    active: dev
  application:
    name: demo-client
  boot:
    admin:
      client:
        url: http://localhost:8000
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false


swagger:
  enable: true
  base-package: com.anything.boot.gateway.app


demo:
  name: test
  birth-year: 2000
  list:
    - one
    - two
    - three
  set: [1,2,3]
  map:
    name: xiaoming
    age: 21


management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  hystrix:
    enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 10
  command:
    default:
      fallback:
        enabled: true
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 1000