spring:
  profiles:
    active: dev
  application:
    name: boot-demo
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: service-producer
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: false

swagger:
  enable: true
  base-package: com.anything.boot.gateway.app


demo:
  name: test
  birth-year: 2000
  list:
    - one
    - two
    - three
  set: [1,2,3]
  map:
    name: xiaoming
    age: 21

feign:
  hystrix:
    enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 10
  command:
    default:
      fallback:
        enabled: false
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 1000